<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.dwkshop</groupId>
    <artifactId>dwkshop-services</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>dwkshop-services</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <modules>
        <module>backend-migrator</module>
        <module>backend-common</module>
        <module>backend-auth</module>
        <module>backend-product</module>
        <module>backend-cart</module>
        <module>backend-member</module>
        <module>backend-marketing</module>
        <module>backend-order</module>
        <module>backend-aftersale</module>
        <module>backend-gateway</module>
    </modules>
</project>
