CREATE TABLE dwkshop_order.payment_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  payment_no VARCHAR(64) NOT NULL,
  order_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  channel VARCHAR(30) NOT NULL,
  amount INT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'INIT',
  request_no VARCHAR(64) NULL,
  channel_trade_no VARCHAR(128) NULL,
  paid_at DATETIME NULL,
  closed_at DATETIME NULL,
  callback_payload LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_payment_order_no (payment_no),
  UNIQUE KEY uk_payment_order_order_id (order_id),
  KEY idx_payment_order_user_id (user_id),
  KEY idx_payment_order_status (status),
  KEY idx_payment_order_request_no (request_no),
  CONSTRAINT fk_payment_order_trade_order FOREIGN KEY (order_id) REFERENCES dwkshop_order.trade_order (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE dwkshop_order.payment_transaction (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  payment_no VARCHAR(64) NOT NULL,
  order_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  channel VARCHAR(30) NOT NULL,
  amount INT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'INIT',
  request_no VARCHAR(64) NOT NULL,
  channel_trade_no VARCHAR(128) NULL,
  paid_at DATETIME NULL,
  closed_at DATETIME NULL,
  callback_payload LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_payment_transaction_request_no (request_no),
  KEY idx_payment_transaction_payment_no (payment_no),
  KEY idx_payment_transaction_order_id (order_id),
  KEY idx_payment_transaction_user_id (user_id),
  KEY idx_payment_transaction_status (status),
  KEY idx_payment_transaction_channel_trade_no (channel_trade_no),
  CONSTRAINT fk_payment_transaction_order FOREIGN KEY (payment_no) REFERENCES dwkshop_order.payment_order (payment_no),
  CONSTRAINT fk_payment_transaction_trade_order FOREIGN KEY (order_id) REFERENCES dwkshop_order.trade_order (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
