ALTER TABLE product
  ADD COLUMN brand_name VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN support_refund BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN snapshot_version INT NOT NULL DEFAULT 1;

ALTER TABLE trade_order_item
  ADD COLUMN spec_json TEXT NULL,
  ADD COLUMN category_id BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN brand_name VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN delivery_type VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  ADD COLUMN support_point_deduction BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN snapshot_version INT NOT NULL DEFAULT 1;
