package com.dwkshop.backend;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
@Profile("test")
class TestAuditSchemaConfiguration {

    @Bean
    InitializingBean initializeAuditSchema(JdbcTemplate jdbcTemplate) {
        return () -> {
            jdbcTemplate.execute("CREATE SCHEMA IF NOT EXISTS dwkshop_audit");
            jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS dwkshop_audit.admin_operation_log (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operator_id BIGINT NULL,
                    operator_name VARCHAR(64) NOT NULL,
                    operation_type VARCHAR(64) NOT NULL,
                    biz_type VARCHAR(64) NOT NULL,
                    biz_id BIGINT NULL,
                    before_value CLOB NULL,
                    after_value CLOB NULL,
                    reason VARCHAR(500) NOT NULL,
                    ip VARCHAR(64) NULL,
                    user_agent VARCHAR(255) NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        };
    }
}
