plugins {
    id "com.android.application"
}

android {
    namespace "com.dwkshop.android"
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.dwkshop.android"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
        buildConfigField "String", "API_BASE_URL", "\"http://10.0.2.2:8080\""
    }
}
